name: tfm_compas
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - plotly=5.22.0
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - scipy=1.12.0
  - statsmodels=0.14.2
  - jupyterlab=4.1.6
  - ipykernel=6.29.4
  - sqlalchemy=2.0.29
  - mysql-connector-python=8.4.0
  - pip
  - pip:
      - python-dotenv==1.0.1
      - pyyaml==6.0.1
