name: CI - Ejecutar notebooks TFM
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true  # baja binarios si usas Git LFS

      - name: Configurar Python 3.12.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          # Quita cualquier línea 'python==' de requirements (defensivo)
          for f in requirements_tfm.txt requirements.txt; do
            if [ -f "$f" ]; then sed -i '/^python[<=>]/d' "$f"; fi
          done
          if [ -f requirements_tfm.txt ]; then
            pip install -r requirements_tfm.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install jupyter nbconvert nbclient nbformat ipykernel numpy pandas scikit-learn matplotlib plotly seaborn
          fi
          # Libs usadas en lib_propias y lectura de ficheros
          pip install missingno==0.5.2 openpyxl pyarrow
          pip install fuzzywuzzy==0.18.0
          pip install python-Levenshtein

      - name: Exportar PYTHONPATH (repo root y /lib)
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/lib" >> $GITHUB_ENV

      - name: Hacer visible lib_propias sin tocar notebooks
        run: |
          if [ -f lib/lib_propias.py ]; then cp lib/lib_propias.py .; fi

      - name: Preparar carpetas
        run: mkdir -p data/raw_propublica data/processed export_dashboard

      - name: "Debug: árbol del repo"
        run: |
          echo "== pwd ==" && pwd
          echo "== notebooks ==" && ls -lah notebooks || true
          echo "== data/raw_propublica ==" && ls -lah data/raw_propublica || true
          echo "== export_dashboard ==" && ls -lah export_dashboard || true

      - name: Inspeccionar CSVs (tamaño + 5 primeras líneas)
        run: |
          for f in compas-scores-raw.csv compas-scores-two-years.csv; do
            p="data/raw_propublica/$f"
            echo "== $p =="
            if [ -f "$p" ]; then
              echo "-- bytes --"; wc -c "$p" || true
              echo "-- head --"; head -n 5 "$p" || true
            else
              echo "NO ENCONTRADO"
            fi
            echo
          done

      - name: Validar que los CSVs no están vacíos
        run: |
          for p in data/raw_propublica/compas-scores-raw.csv data/raw_propublica/compas-scores-two-years.csv; do
            if [ ! -f "$p" ]; then
              echo "::error::No existe $p"; exit 1;
            fi
            BYTES=$(wc -c < "$p")
            if [ "$BYTES" -lt 10 ]; then
              echo "::error::$p está vacío o es un puntero LFS"; exit 1;
            fi
          done

      - name: Ejecutar notebook 1 (comodín)
        run: |
          NB1=$(ls -1 notebooks/1_*.ipynb 2>/dev/null | head -n 1 || true)
          if [ -z "$NB1" ]; then echo "::error::No se encontró notebooks/1_*.ipynb"; exit 1; fi
          echo "Ejecutando: $NB1"
          jupyter nbconvert --execute --to notebook --inplace --ExecutePreprocessor.timeout=1200 "$NB1"

      - name: Ejecutar notebook 2 (comodín)
        run: |
          NB2=$(ls -1 notebooks/2_*.ipynb 2>/dev/null | head -n 1 || true)
          if [ -z "$NB2" ]; then echo "::error::No se encontró notebooks/2_*.ipynb"; exit 1; fi
          echo "Ejecutando: $NB2"
          jupyter nbconvert --execute --to notebook --inplace --ExecutePreprocessor.timeout=1200 "$NB2"

      - name: Ejecutar notebook 3 (comodín)
        run: |
          NB3=$(ls -1 notebooks/3_*.ipynb 2>/dev/null | head -n 1 || true)
          if [ -z "$NB3" ]; then echo "::error::No se encontró notebooks/3_*.ipynb"; exit 1; fi
          echo "Ejecutando: $NB3"
          jupyter nbconvert --execute --to notebook --inplace --ExecutePreprocessor.timeout=1200 "$NB3"

      - name: Comprobar salidas (si aplican)
        run: |
          if [ -f export_dashboard/metricas_globales.csv ]; then
            echo "OK: export_dashboard/metricas_globales.csv"
          else
            echo "AVISO: falta export_dashboard/metricas_globales.csv"
          fi
          if [ -f export_dashboard/metricas_por_grupo.csv ]; then
            echo "OK: export_dashboard/metricas_por_grupo.csv"
          else
            echo "AVISO: falta export_dashboard/metricas_por_grupo.csv"
          fi

